### ISSUE TITLE
是否支持下歷史記錄和顯示註釋

### ISSUE THREAD

**Issue by lingchuanbo** [stansu/stankey#1]
您好 能否新增加
1.動態過濾顯示 比如我輸入a 列表顯示aa ab a*相關的功能
2.增加歷史狀態 默認顯示10個 按熱度排序 比如這樣（Find+Run Robot）
![image](https://user-images.githubusercontent.com/4213515/48936943-7b96d880-ef47-11e8-9997-dd0f058a0e54.png)
3.功能註釋 例如輸入aa 在邊上灰色顯示該功能描述
謝謝！

**Comment by stansu** [comment]
> 您好 能否新增加
> 1.動態過濾顯示 比如我輸入a 列表顯示aa ab a*相關的功能
> 2.增加歷史狀態 默認顯示10個 按熱度排序 比如這樣（Find+Run Robot）
> ![image](https://user-images.githubusercontent.com/4213515/48936943-7b96d880-ef47-11e8-9997-dd0f058a0e54.png)
> 3.功能註釋 例如輸入aa 在邊上灰色顯示該功能描述
> 謝謝！

我目前focus在blender，所以没有打算继续投入3dsmax的开发

**Comment by stansu** [comment]
> 您好 能否新增加
> 1.動態過濾顯示 比如我輸入a 列表顯示aa ab a*相關的功能
> 2.增加歷史狀態 默認顯示10個 按熱度排序 比如這樣（Find+Run Robot）
> ![image](https://user-images.githubusercontent.com/4213515/48936943-7b96d880-ef47-11e8-9997-dd0f058a0e54.png)
> 3.功能註釋 例如輸入aa 在邊上灰色顯示該功能描述
> 謝謝！

我目前focus在blender，所以没有打算继续投入3dsmax的开发
